Fix same-name variable/func param swift bug. * Somehow, when using a same-name variable inside the body of a swift function   that matches with the same-name of a function parameter, a swift llvm bug incurs   a strange indirection that causes the function parameter's type to mutate into the   same-name variable's type.
  Example:
  error: value of type 'FnDecl' has no member 'span'.